-- SimpleEdu LMS Database Schema
-- Auto-generated by installer

SET FOREIGN_KEY_CHECKS = 0;

-- Users table
CREATE TABLE IF NOT EXISTS `{PREFIX}users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `full_name` VARCHAR(100) NOT NULL,
    `email` VARCHAR(150) UNIQUE NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `role` ENUM('admin','guru','siswa','wali_kelas','orang_tua') NOT NULL DEFAULT 'siswa',
    `avatar` VARCHAR(255) DEFAULT NULL,
    `phone` VARCHAR(20) DEFAULT NULL,
    `bio` TEXT DEFAULT NULL,
    `nis` VARCHAR(20) DEFAULT NULL,
    `nip` VARCHAR(30) DEFAULT NULL,
    `class_id` INT DEFAULT NULL,
    `competency_id` INT DEFAULT NULL,
    `birth_date` DATE DEFAULT NULL,
    `theme` VARCHAR(10) DEFAULT 'light',
    `status` ENUM('pending','active','suspended') DEFAULT 'pending',
    `xp_points` INT DEFAULT 0,
    `level` INT DEFAULT 1,
    `last_login` DATETIME DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Settings table
CREATE TABLE IF NOT EXISTS `{PREFIX}settings` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `setting_key` VARCHAR(100) UNIQUE NOT NULL,
    `setting_value` TEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Classes table
CREATE TABLE IF NOT EXISTS `{PREFIX}classes` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `grade` VARCHAR(10) NOT NULL,
    `major` VARCHAR(100) DEFAULT NULL,
    `academic_year` VARCHAR(20) NOT NULL,
    `homeroom_teacher_id` INT DEFAULT NULL,
    `description` TEXT DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`homeroom_teacher_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Class members
CREATE TABLE IF NOT EXISTS `{PREFIX}class_members` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `class_id` INT NOT NULL,
    `user_id` INT NOT NULL,
    `role` ENUM('teacher','student') NOT NULL DEFAULT 'student',
    `joined_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`class_id`) REFERENCES `{PREFIX}classes`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`user_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `unique_member` (`class_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Subjects/Courses
CREATE TABLE IF NOT EXISTS `{PREFIX}subjects` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `class_id` INT NOT NULL,
    `teacher_id` INT NOT NULL,
    `name` VARCHAR(150) NOT NULL,
    `description` TEXT DEFAULT NULL,
    `color` VARCHAR(7) DEFAULT '#3B49DF',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`class_id`) REFERENCES `{PREFIX}classes`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`teacher_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Materials
CREATE TABLE IF NOT EXISTS `{PREFIX}materials` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `subject_id` INT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `content` LONGTEXT DEFAULT NULL,
    `type` ENUM('text','video','file','link') DEFAULT 'text',
    `file_path` VARCHAR(500) DEFAULT NULL,
    `video_url` VARCHAR(500) DEFAULT NULL,
    `order_num` INT DEFAULT 0,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`subject_id`) REFERENCES `{PREFIX}subjects`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Assignments
CREATE TABLE IF NOT EXISTS `{PREFIX}assignments` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `subject_id` INT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` LONGTEXT DEFAULT NULL,
    `type` ENUM('file','text','both') DEFAULT 'both',
    `max_score` INT DEFAULT 100,
    `deadline` DATETIME NOT NULL,
    `allow_late` TINYINT(1) DEFAULT 0,
    `allow_revision` TINYINT(1) DEFAULT 1,
    `max_file_size` INT DEFAULT 10485760,
    `allowed_types` VARCHAR(255) DEFAULT 'pdf,doc,docx,jpg,jpeg,png',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`subject_id`) REFERENCES `{PREFIX}subjects`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Assignment submissions
CREATE TABLE IF NOT EXISTS `{PREFIX}submissions` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `assignment_id` INT NOT NULL,
    `student_id` INT NOT NULL,
    `content` LONGTEXT DEFAULT NULL,
    `file_path` VARCHAR(500) DEFAULT NULL,
    `file_name` VARCHAR(255) DEFAULT NULL,
    `score` DECIMAL(5,2) DEFAULT NULL,
    `feedback` TEXT DEFAULT NULL,
    `graded_by` INT DEFAULT NULL,
    `graded_at` DATETIME DEFAULT NULL,
    `revision_count` INT DEFAULT 0,
    `status` ENUM('submitted','graded','revision','late') DEFAULT 'submitted',
    `submitted_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`assignment_id`) REFERENCES `{PREFIX}assignments`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`student_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`graded_by`) REFERENCES `{PREFIX}users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Quizzes
CREATE TABLE IF NOT EXISTS `{PREFIX}quizzes` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `subject_id` INT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT DEFAULT NULL,
    `duration_minutes` INT DEFAULT 60,
    `max_attempts` INT DEFAULT 1,
    `shuffle_questions` TINYINT(1) DEFAULT 1,
    `shuffle_options` TINYINT(1) DEFAULT 1,
    `show_result` TINYINT(1) DEFAULT 1,
    `passing_score` INT DEFAULT 70,
    `start_time` DATETIME DEFAULT NULL,
    `end_time` DATETIME DEFAULT NULL,
    `status` ENUM('draft','active','closed') DEFAULT 'draft',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`subject_id`) REFERENCES `{PREFIX}subjects`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Quiz questions
CREATE TABLE IF NOT EXISTS `{PREFIX}quiz_questions` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `quiz_id` INT NOT NULL,
    `question` LONGTEXT NOT NULL,
    `type` ENUM('multiple_choice','essay','true_false') DEFAULT 'multiple_choice',
    `options` JSON DEFAULT NULL,
    `correct_answer` TEXT DEFAULT NULL,
    `points` INT DEFAULT 1,
    `order_num` INT DEFAULT 0,
    FOREIGN KEY (`quiz_id`) REFERENCES `{PREFIX}quizzes`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Quiz attempts
CREATE TABLE IF NOT EXISTS `{PREFIX}quiz_attempts` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `quiz_id` INT NOT NULL,
    `student_id` INT NOT NULL,
    `answers` JSON DEFAULT NULL,
    `score` DECIMAL(5,2) DEFAULT NULL,
    `started_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `finished_at` DATETIME DEFAULT NULL,
    `status` ENUM('in_progress','completed','timeout') DEFAULT 'in_progress',
    FOREIGN KEY (`quiz_id`) REFERENCES `{PREFIX}quizzes`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`student_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Attendance
CREATE TABLE IF NOT EXISTS `{PREFIX}attendance` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `class_id` INT NOT NULL,
    `subject_id` INT DEFAULT NULL,
    `student_id` INT NOT NULL,
    `date` DATE NOT NULL,
    `status` ENUM('hadir','izin','sakit','alpha') NOT NULL DEFAULT 'hadir',
    `note` VARCHAR(255) DEFAULT NULL,
    `recorded_by` INT DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`class_id`) REFERENCES `{PREFIX}classes`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`student_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`recorded_by`) REFERENCES `{PREFIX}users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Announcements
CREATE TABLE IF NOT EXISTS `{PREFIX}announcements` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `content` LONGTEXT NOT NULL,
    `author_id` INT NOT NULL,
    `target` ENUM('all','class','role') DEFAULT 'all',
    `target_id` INT DEFAULT NULL,
    `target_role` VARCHAR(20) DEFAULT NULL,
    `is_pinned` TINYINT(1) DEFAULT 0,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`author_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Forum categories
CREATE TABLE IF NOT EXISTS `{PREFIX}forum_categories` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `description` TEXT DEFAULT NULL,
    `icon` VARCHAR(50) DEFAULT '💬',
    `order_num` INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Forum posts
CREATE TABLE IF NOT EXISTS `{PREFIX}forum_posts` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `category_id` INT NOT NULL,
    `author_id` INT NOT NULL,
    `subject_id` INT DEFAULT NULL,
    `title` VARCHAR(255) NOT NULL,
    `content` LONGTEXT NOT NULL,
    `attachment` VARCHAR(500) DEFAULT NULL,
    `views` INT DEFAULT 0,
    `is_pinned` TINYINT(1) DEFAULT 0,
    `is_locked` TINYINT(1) DEFAULT 0,
    `edited_at` DATETIME DEFAULT NULL,
    `edited_by` INT DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`category_id`) REFERENCES `{PREFIX}forum_categories`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`author_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Forum replies
CREATE TABLE IF NOT EXISTS `{PREFIX}forum_replies` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `post_id` INT NOT NULL,
    `author_id` INT NOT NULL,
    `parent_reply_id` INT DEFAULT NULL,
    `content` LONGTEXT NOT NULL,
    `attachment` VARCHAR(500) DEFAULT NULL,
    `edited_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`post_id`) REFERENCES `{PREFIX}forum_posts`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`author_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Forum likes
CREATE TABLE IF NOT EXISTS `{PREFIX}forum_likes` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `post_id` INT DEFAULT NULL,
    `reply_id` INT DEFAULT NULL,
    `user_id` INT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Schedule
CREATE TABLE IF NOT EXISTS `{PREFIX}schedules` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `class_id` INT NOT NULL,
    `subject_id` INT NOT NULL,
    `day_of_week` TINYINT NOT NULL COMMENT '1=Monday, 7=Sunday',
    `start_time` TIME NOT NULL,
    `end_time` TIME NOT NULL,
    `room` VARCHAR(50) DEFAULT NULL,
    FOREIGN KEY (`class_id`) REFERENCES `{PREFIX}classes`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`subject_id`) REFERENCES `{PREFIX}subjects`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Grades
CREATE TABLE IF NOT EXISTS `{PREFIX}grades` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `student_id` INT NOT NULL,
    `subject_id` INT NOT NULL,
    `type` ENUM('tugas','quiz','uts','uas','praktek') NOT NULL,
    `title` VARCHAR(255) DEFAULT NULL,
    `score` DECIMAL(5,2) NOT NULL,
    `max_score` DECIMAL(5,2) DEFAULT 100,
    `semester` TINYINT DEFAULT 1,
    `academic_year` VARCHAR(20) DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`student_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`subject_id`) REFERENCES `{PREFIX}subjects`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Competencies (SMK)
CREATE TABLE IF NOT EXISTS `{PREFIX}competencies` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(200) NOT NULL,
    `code` VARCHAR(50) DEFAULT NULL,
    `description` TEXT DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Badges
CREATE TABLE IF NOT EXISTS `{PREFIX}badges` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `description` VARCHAR(255) DEFAULT NULL,
    `icon` VARCHAR(100) DEFAULT '🏆',
    `xp_reward` INT DEFAULT 0,
    `criteria_type` VARCHAR(50) DEFAULT NULL,
    `criteria_value` INT DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User badges
CREATE TABLE IF NOT EXISTS `{PREFIX}user_badges` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `badge_id` INT NOT NULL,
    `earned_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`badge_id`) REFERENCES `{PREFIX}badges`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `unique_badge` (`user_id`, `badge_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- XP Log
CREATE TABLE IF NOT EXISTS `{PREFIX}xp_log` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `points` INT NOT NULL,
    `reason` VARCHAR(255) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PKL (Praktek Kerja Lapangan)
CREATE TABLE IF NOT EXISTS `{PREFIX}pkl` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `student_id` INT NOT NULL,
    `company_name` VARCHAR(200) NOT NULL,
    `company_address` TEXT DEFAULT NULL,
    `supervisor_name` VARCHAR(100) DEFAULT NULL,
    `supervisor_phone` VARCHAR(20) DEFAULT NULL,
    `start_date` DATE NOT NULL,
    `end_date` DATE NOT NULL,
    `status` ENUM('pending','active','completed') DEFAULT 'pending',
    `final_score` DECIMAL(5,2) DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`student_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PKL Journals
CREATE TABLE IF NOT EXISTS `{PREFIX}pkl_journals` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `pkl_id` INT NOT NULL,
    `date` DATE NOT NULL,
    `activity` TEXT NOT NULL,
    `notes` TEXT DEFAULT NULL,
    `photo` VARCHAR(500) DEFAULT NULL,
    `verified` TINYINT(1) DEFAULT 0,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`pkl_id`) REFERENCES `{PREFIX}pkl`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Certificates
CREATE TABLE IF NOT EXISTS `{PREFIX}certificates` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT DEFAULT NULL,
    `issuer` VARCHAR(200) DEFAULT NULL,
    `file_path` VARCHAR(500) DEFAULT NULL,
    `issued_date` DATE DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Portfolio
CREATE TABLE IF NOT EXISTS `{PREFIX}portfolio` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT DEFAULT NULL,
    `category` VARCHAR(100) DEFAULT NULL,
    `file_path` VARCHAR(500) DEFAULT NULL,
    `link_url` VARCHAR(500) DEFAULT NULL,
    `thumbnail` VARCHAR(500) DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Notifications
CREATE TABLE IF NOT EXISTS `{PREFIX}notifications` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `message` TEXT DEFAULT NULL,
    `type` VARCHAR(50) DEFAULT 'info',
    `link` VARCHAR(500) DEFAULT NULL,
    `is_read` TINYINT(1) DEFAULT 0,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Parent-Student relationship
CREATE TABLE IF NOT EXISTS `{PREFIX}parent_student` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `parent_id` INT NOT NULL,
    `student_id` INT NOT NULL,
    FOREIGN KEY (`parent_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`student_id`) REFERENCES `{PREFIX}users`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `unique_relation` (`parent_id`, `student_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default forum categories
INSERT INTO `{PREFIX}forum_categories` (`name`, `description`, `icon`, `order_num`) VALUES
('Umum', 'Diskusi umum seputar sekolah', '💬', 1),
('Coding & Programming', 'Tanya jawab seputar pemrograman', '💻', 2),
('Jaringan & Infrastruktur', 'Diskusi jaringan komputer', '🌐', 3),
('Desain & Multimedia', 'Sharing karya desain', '🎨', 4),
('PKL & Magang', 'Forum diskusi PKL', '🏢', 5),
('Tips & Tutorial', 'Berbagi tips dan tutorial', '📝', 6);

-- Insert default badges
INSERT INTO `{PREFIX}badges` (`name`, `description`, `icon`, `xp_reward`, `criteria_type`, `criteria_value`) VALUES
('Pemula', 'Selamat datang di SimpleEdu!', '🌟', 10, 'login', 1),
('Rajin', 'Login 7 hari berturut-turut', '🔥', 50, 'streak', 7),
('Penanya', 'Membuat 10 post di forum', '❓', 30, 'posts', 10),
('Penolong', 'Membalas 25 diskusi di forum', '🤝', 50, 'replies', 25),
('Siswa Teladan', 'Nilai rata-rata di atas 90', '🏆', 100, 'avg_score', 90),
('Tepat Waktu', 'Submit 10 tugas sebelum deadline', '⏰', 40, 'on_time', 10),
('Quiz Master', 'Score sempurna di 5 quiz', '🧠', 80, 'perfect_quiz', 5),
('Portofolio Pro', 'Upload 10 karya portfolio', '🎯', 60, 'portfolio', 10);

SET FOREIGN_KEY_CHECKS = 1;
